import {agencies,parseReport,parseMaster,summarize} from './data.mjs';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>n===null?'Not available':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100);
let master=[],reports={},selected=new Set();
const agency=()=>$('agency').value;
function groups(){return [...new Set([...agencies[agency()],...master.filter(x=>x.agency===agency()).map(x=>x.group)])];}
function table(headers,rows){return '<div class="tablewrap"><table><thead><tr>'+headers.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';}
function setup(){selected=new Set(groups());$('upload-heading').textContent=agency()==='G-8'?'Directorate uploads':'DASA uploads';$('uploads').innerHTML='<div class="tablewrap"><table><thead><tr><th>Group</th><th>Obligation report</th><th>Unsubmitted vouchers</th></tr></thead><tbody>'+groups().map(g=>'<tr><td>'+esc(g)+'</td>'+['travel','voucher'].map(k=>'<td><input aria-label="'+esc(g+' '+k)+'" type="file" accept=".csv" data-group="'+esc(g)+'" data-kind="'+k+'"><p class="muted">'+esc(reports[agency()+'|'+g+'|'+k]?.filename||'Not supplied')+'</p></td>').join('')+'</tr>').join('')+'</tbody></table></div>';$('filters').innerHTML='<legend>'+(agency()==='G-8'?'Directorates':'DASA’s')+'</legend>'+groups().map(g=>'<label><input type="checkbox" value="'+esc(g)+'" checked>'+esc(g)+'</label>').join('');render();}
function render(){const items=summarize(master,reports,agency(),[...selected]),sum=k=>items.reduce((n,x)=>n+(x[k]||0),0),incomplete=items.some(x=>x.obligated===null),completed=items.flatMap(x=>x.completed),vouchers=items.flatMap(x=>x.unsubmitted);$('metrics').innerHTML=[['Budget',money(sum('budget'))],['Funding received',money(sum('received'))],['Reported obligations',money(sum('obligated'))+(incomplete?' *':'')],['Unsubmitted vouchers',vouchers.length]].map(([l,v])=>'<article class="metric">'+l+'<b>'+esc(v)+'</b></article>').join('');$('funding').innerHTML=(incomplete?'<p class="muted">* Partial total: one or more obligation reports have not been supplied. Missing budgets and reports are not treated as confirmed zero balances.</p>':'')+table(['Group','Budget','Received','Obligated','Remaining','Travel report','Voucher report'],items.map(x=>[x.group,money(x.budget),money(x.received),money(x.obligated),money(x.remaining),x.travelStatus,x.voucherStatus]));$('vouchers').innerHTML=vouchers.length?table(['Group','Traveler','Document','Departure','Days since trip ended','Authorized'],vouchers.map(r=>[r.group,r.traveler,r.document,r.departure,r.days,money(r.authorized)])):'<p>No unsubmitted-voucher records in the supplied files.</p>';$('completed').innerHTML=completed.length?table(['Group','Traveler','Document','Departure','Destination','Voucher amount'],completed.map(r=>[r.group,r.traveler,r.document,r.departure,r.destination,money(r.voucherAmount)])):'<p>No travel with recorded voucher amounts in the supplied files.</p>';}
$('agency').addEventListener('change',setup);$('filters').addEventListener('change',e=>{e.target.checked?selected.add(e.target.value):selected.delete(e.target.value);render();});$('process').addEventListener('click',()=>{$('dashboard').hidden=false;render();});$('print').addEventListener('click',()=>window.print());
$('master').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const w=new ExcelJS.Workbook();await w.xlsx.load(await f.arrayBuffer());const rows=[];w.worksheets[0].eachRow(r=>rows.push(r.values.slice(1).map(v=>v&&typeof v==='object'?'result'in v?v.result:v.text||'':v)));master=parseMaster(rows);$('save-master').hidden=false;$('master-status').textContent=f.name+' ready for review. Publish to replace the shared master for everyone.';$('message').textContent='Master loaded. Review any unmatched group names before relying on balances.';setup();}catch(err){$('message').textContent=err.message;}e.target.value='';});
$('uploads').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const {group,kind}=e.target.dataset;const parsed=parseReport(await f.text(),kind,agency(),group);const destinations=new Set([group,...parsed.rows.map(r=>r.group)]);for(const destination of destinations)reports[agency()+'|'+destination+'|'+kind]={...parsed,rows:parsed.rows.filter(r=>r.group===destination),filename:f.name};$('message').textContent=parsed.rows.length+' records loaded for '+group+(parsed.duplicates?'; '+parsed.duplicates+' duplicate accounting lines skipped.':'.');setup();}catch(err){$('message').textContent=err.message;e.target.value='';}});setup();

async function loadShared(){try{const response=await fetch('/api/master',{cache:'no-store'});if(!response.ok)throw Error('Shared master is not available yet.');const saved=await response.json();master=saved.rows||[];$('master-status').textContent=saved.updatedAt?'Shared master updated '+new Date(saved.updatedAt).toLocaleString():'No shared master yet. Sign in and upload the master budget.';setup();}catch(e){$('master-status').textContent=e.message;}}
$('save-master').addEventListener('click',async()=>{const button=$('save-master');button.disabled=true;try{const r=await fetch('/api/master',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({rows:master})});if(r.status===401||r.status===403)throw Error('Sign in before publishing the shared master.');const data=await r.json();if(!r.ok)throw Error(data.error||'Could not save master.');master=data.rows;button.hidden=true;$('master-status').textContent='Shared master updated '+new Date(data.updatedAt).toLocaleString();$('message').textContent='Master budget saved for all dashboard visitors.';}catch(e){$('message').textContent=e.message;}finally{button.disabled=false;}});loadShared();
