import {agencies,parseReport,parseMaster,summarize} from './data.mjs';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>n===null?'Not available':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100);
let master=[],reports={},selected=new Set(),masterSource=null;
const password=()=>$('upload-password').value;
const requirePassword=()=>{if(!password())throw Error('Enter the master upload password before uploading.');};
const agency=()=>$('agency').value;
function groups(){return [...new Set([...agencies[agency()],...master.filter(x=>x.agency===agency()).map(x=>x.group)])];}
function table(headers,rows){return '<div class="tablewrap"><table><thead><tr>'+headers.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';}
function setup(){selected=new Set(groups());$('upload-heading').textContent=agency()==='G-8'?'Directorate uploads':'DASA uploads';$('uploads').innerHTML='<div class="tablewrap"><table><thead><tr><th>Group</th><th>Obligation report</th><th>Unsubmitted vouchers</th></tr></thead><tbody>'+groups().map(g=>'<tr><td>'+esc(g)+'</td>'+['travel','voucher'].map(k=>'<td><input aria-label="'+esc(g+' '+k)+'" type="file" accept=".csv" data-group="'+esc(g)+'" data-kind="'+k+'"><p class="muted">'+esc(reports[agency()+'|'+g+'|'+k]?.filename||'Not supplied')+'</p></td>').join('')+'</tr>').join('')+'</tbody></table></div>';$('filters').innerHTML='<legend>'+(agency()==='G-8'?'Directorates':'DASA’s')+'</legend>'+groups().map(g=>'<label><input type="checkbox" value="'+esc(g)+'" checked>'+esc(g)+'</label>').join('');render();}
function render(){const items=summarize(master,reports,agency(),[...selected]),sum=k=>items.reduce((n,x)=>n+(x[k]||0),0),incomplete=items.some(x=>x.obligated===null),completed=items.flatMap(x=>x.completed),vouchers=items.flatMap(x=>x.unsubmitted);$('metrics').innerHTML=[['Budget',money(sum('budget'))],['Funding received',money(sum('received'))],['Reported obligations',money(sum('obligated'))+(incomplete?' *':'')],['Unsubmitted vouchers',vouchers.length]].map(([l,v])=>'<article class="metric">'+l+'<b>'+esc(v)+'</b></article>').join('');$('funding').innerHTML=(incomplete?'<p class="muted">* Partial total: one or more obligation reports have not been supplied. Missing budgets and reports are not treated as confirmed zero balances.</p>':'')+table(['Group','Budget','Received','Obligated','Remaining','Travel report','Voucher report'],items.map(x=>[x.group,money(x.budget),money(x.received),money(x.obligated),money(x.remaining),x.travelStatus,x.voucherStatus]));$('vouchers').innerHTML=vouchers.length?table(['Group','Traveler','Document','Departure','Days since trip ended','Authorized'],vouchers.map(r=>[r.group,r.traveler,r.document,r.departure,r.days,money(r.authorized)])):'<p>No unsubmitted-voucher records in the supplied files.</p>';$('completed').innerHTML=completed.length?table(['Group','Traveler','Document','Departure','Destination','Voucher amount'],completed.map(r=>[r.group,r.traveler,r.document,r.departure,r.destination,money(r.voucherAmount)])):'<p>No travel with recorded voucher amounts in the supplied files.</p>';}
$('agency').addEventListener('change',setup);$('filters').addEventListener('change',e=>{e.target.checked?selected.add(e.target.value):selected.delete(e.target.value);render();});$('process').addEventListener('click',()=>{$('dashboard').hidden=false;render();});$('print').addEventListener('click',()=>window.print());
$('master').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{requirePassword();if(f.size>10000000)throw Error("Master file exceeds 10 MB.");const bytes=new Uint8Array(await f.arrayBuffer());let binary="";for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));masterSource=btoa(binary);const w=new ExcelJS.Workbook();await w.xlsx.load(await f.arrayBuffer());const rows=[];w.worksheets[0].eachRow(r=>rows.push(r.values.slice(1).map(v=>v&&typeof v==='object'?'result'in v?v.result:v.text||'':v)));master=parseMaster(rows);$('save-master').hidden=false;$('master-status').textContent=f.name+' ready for review. Publish to replace the shared master for everyone.';$('message').textContent='Master loaded. Review any unmatched group names before relying on balances.';setup();}catch(err){$('message').textContent=err.message;}e.target.value='';});
$('uploads').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;const input=e.target;try{requirePassword();if(f.size>10000000)throw Error('Report exceeds 10 MB.');input.disabled=true;const {group,kind}=input.dataset;const selectedAgency=agency();const text=await f.text();parseReport(text,kind,selectedAgency,group);const response=await fetch('/api/reports',{method:'PUT',headers:{'Content-Type':'application/json','x-upload-password':password()},body:JSON.stringify({agency:selectedAgency,group,kind,text,filename:f.name})});const data=await response.json();if(!response.ok)throw Error(data.error||'Unable to save report.');reports[selectedAgency+'|'+group+'|'+kind]=data.report;$('message').textContent=data.report.rows.length+' records saved in Azure for '+group+'. Only this upload slot was replaced.';setup();}catch(err){$('message').textContent=err.message;}finally{input.disabled=false;input.value='';}});setup();

async function loadShared(){try{const response=await fetch('/api/master',{cache:'no-store'});if(!response.ok)throw Error('Shared master is not available yet.');const saved=await response.json();master=saved.rows||[];$('master-status').textContent=saved.updatedAt?'Shared master updated '+new Date(saved.updatedAt).toLocaleString():'No shared master yet. Enter the upload password and upload the master budget.';setup();}catch(e){$('master-status').textContent=e.message;}}
$('save-master').addEventListener('click',async()=>{const button=$('save-master');button.disabled=true;try{requirePassword();const r=await fetch('/api/master',{method:'PUT',headers:{'Content-Type':'application/json','x-upload-password':password()},body:JSON.stringify({rows:master,sourceBase64:masterSource})});if(r.status===401||r.status===403)throw Error('Enter the correct master upload password.');const data=await r.json();if(!r.ok)throw Error(data.error||'Could not save master.');master=data.rows;button.hidden=true;$('master-status').textContent='Shared master updated '+new Date(data.updatedAt).toLocaleString();$('message').textContent='Master budget saved for all dashboard visitors.';}catch(e){$('message').textContent=e.message;}finally{button.disabled=false;}});loadShared();

async function loadReports(){try{const r=await fetch('/api/reports',{cache:'no-store'});if(!r.ok)throw Error('Saved reports could not be loaded.');const data=await r.json();reports={...data.reports,...reports};setup();}catch(e){$('message').textContent=e.message;}}
loadReports();
