import {agencies,canonical,parseReport,parseMaster,summarize} from './data.mjs';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>n===null?'Not available':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100);
let master=[],reports={},selected=new Set(),expandedCompleted=new Set(),masterSource=null,loaMapping,loaOrganizations={},stagedLoas=null;
const password=()=>$('upload-password').value;
const requirePassword=()=>{if(!password())throw Error('Enter the master upload password before uploading.');};
const agency=()=>$('agency').value;
function groups(){return [...new Set([...agencies[agency()],...master.filter(x=>x.agency===agency()&&(agency()==='G-8'||!/^HQs?$/i.test(x.group))).map(x=>x.group)])];}
function table(headers,rows){return '<div class="tablewrap"><table><thead><tr>'+headers.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';}
function completedView(items){const summaries=items.map(item=>({group:item.group,trips:item.completed,total:item.completed.reduce((n,row)=>n+(row.voucherAmount||0),0)})).filter(item=>item.trips.length);if(!summaries.length)return '<p>No travel with recorded voucher amounts in the supplied files.</p>';return '<div class="completed-groups">'+summaries.map(item=>{const open=expandedCompleted.has(item.group);return '<section class="completed-group"><button type="button" class="completed-group-toggle" data-completed-group="'+esc(item.group)+'" aria-expanded="'+open+'"><span><strong>'+esc(item.group)+'</strong><small>Click to '+(open?'hide':'show')+' trip details</small></span><span class="completed-stat"><b>'+item.trips.length+'</b> trip'+(item.trips.length===1?'':'s')+'</span><span class="completed-stat"><b>'+esc(money(item.total))+'</b> total voucher amount</span><span class="completed-chevron" aria-hidden="true">'+(open?'−':'+')+'</span></button><div class="completed-details" '+(open?'':'hidden')+'>'+table(['Traveler','Document','Departure','Destination','Voucher amount'],item.trips.map(row=>[row.traveler,row.document,row.departure,row.destination,money(row.voucherAmount)]))+'</div></section>';}).join('')+'</div>';}
function setup(){selected=new Set(groups());expandedCompleted.clear();$('upload-heading').textContent=agency()==='G-8'?'Directorate uploads':'DASA uploads';$('uploads').innerHTML='<div class="tablewrap"><table><thead><tr><th>Group</th><th>Obligation report</th><th>Unsubmitted vouchers</th></tr></thead><tbody>'+groups().map(g=>'<tr><td>'+esc(g)+'</td>'+['travel','voucher'].map(k=>'<td><input aria-label="'+esc(g+' '+k)+'" type="file" accept=".csv" multiple data-group="'+esc(g)+'" data-kind="'+k+'"><p class="muted">'+esc(reports[agency()+'|'+g+'|'+k]?.filename||'Not supplied')+'</p>'+(k==='voucher'&&reports[agency()+'|'+g+'|'+k]?'<button type="button" class="remove-voucher" data-group="'+esc(g)+'">Remove file</button>':'')+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';$('filters').innerHTML='<legend>'+(agency()==='G-8'?'Directorates':'DASA’s')+' — select one or more</legend>'+groups().map(g=>'<label><input type="checkbox" value="'+esc(g)+'" checked>'+esc(g)+'</label>').join('');render();}
function render(){const items=summarize(master,reports,agency(),[...selected]),sum=k=>items.reduce((n,x)=>n+(x[k]||0),0),vouchers=items.flatMap(x=>x.unsubmitted),incomplete=items.some(x=>x.obligated===null);$('metrics').innerHTML=[['Budget',money(sum('budget'))],['Funding received',money(sum('received'))],['Reported obligations',money(sum('obligated'))+(incomplete?' *':'')],['Unsubmitted vouchers',vouchers.length]].map(([l,v])=>'<article class="metric">'+l+'<b>'+esc(v)+'</b><button type="button" class="print-card">Print card</button></article>').join('');$('funding').innerHTML=(incomplete?'<p class="muted">* Partial total: one or more obligation reports have not been supplied. Missing budgets and reports are not treated as confirmed zero balances.</p>':'')+table(['Group','Budget','Received','Obligated','Remaining','Travel report','Voucher report'],items.map(x=>[x.group,money(x.budget),money(x.received),money(x.obligated),money(x.remaining),x.travelStatus,x.voucherStatus]));$('vouchers').innerHTML=vouchers.length?table(['Group','Traveler','Document','Departure','Days since trip ended','Authorized'],vouchers.map(r=>[r.group,r.traveler,r.document,r.departure,r.days,money(r.authorized)])):'<p>No unsubmitted-voucher records in the supplied files.</p>';$('completed').innerHTML=completedView(items);}
function replacementIssues(){if(!stagedLoas)return [];if(!masterSource)return ['Upload a replacement Master budget to complete this LOA update.'];const issues=[];for(const [code,rawGroup] of Object.entries(stagedLoas.mapping)){const group=canonical(rawGroup),organization=stagedLoas.organizations[code],matches=master.filter(row=>row.group===group);if(!matches.length)issues.push(code+': '+group+' is not in the Master budget.');else if(!matches.some(row=>row.agency===organization))issues.push(code+': Organization '+organization+' does not match '+group+' in the Master budget ('+[...new Set(matches.map(row=>row.agency))].join(', ')+').');}return issues;}
function refreshReplacementStatus(){const issues=replacementIssues(),button=$('save-master');$('publish-loas').hidden=true;button.hidden=!masterSource;button.disabled=issues.length>0;button.textContent=stagedLoas?'Publish replacement files':'Publish replacement master';if(stagedLoas){$('loa-status').textContent=issues.length?'Replacement blocked: '+issues.join(' '):Object.keys(stagedLoas.mapping).length+' LOA codes match the staged Master budget and are ready to publish.';}return issues;}
$('agency').addEventListener('change',setup);$('filters').addEventListener('change',e=>{e.target.checked?selected.add(e.target.value):selected.delete(e.target.value);render();});$('completed').addEventListener('click',e=>{const button=e.target.closest('.completed-group-toggle');if(!button)return;const group=button.dataset.completedGroup;expandedCompleted.has(group)?expandedCompleted.delete(group):expandedCompleted.add(group);render();});$('process').addEventListener('click',()=>{$('dashboard').hidden=false;render();});$('print').addEventListener('click',()=>window.print());
$('master').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{requirePassword();if(f.size>10000000)throw Error("Master file exceeds 10 MB.");$('master-status').textContent='Reading '+f.name+'...';const buffer=await f.arrayBuffer(),bytes=new Uint8Array(buffer);let binary="";for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const w=new ExcelJS.Workbook();await w.xlsx.load(buffer);let parsed=null,lastError=null;for(const sheet of w.worksheets){const rows=[];sheet.eachRow(r=>rows.push(r.values.slice(1).map(v=>v&&typeof v==='object'?'result'in v?v.result:v.text||'':v)));try{parsed=parseMaster(rows);break;}catch(err){lastError=err;}}if(!parsed)throw lastError||Error('No readable worksheet was found.');masterSource=btoa(binary);master=parsed;$('master-status').textContent=f.name+' • '+master.length+' budget rows ready to publish.';const issues=refreshReplacementStatus();$('message').textContent=issues.length?issues.join(' '):'Master loaded. Review the dashboard, then publish the replacement files.';setup();}catch(err){masterSource=null;$('save-master').hidden=true;$('master-status').textContent='Upload not staged: '+err.message;$('message').textContent=err.message;refreshReplacementStatus();}e.target.value='';});
$('uploads').addEventListener('change',async e=>{const files=[...(e.target.files||[])];if(!files.length)return;const input=e.target;try{requirePassword();const totalSize=files.reduce((n,f)=>n+f.size,0);if(totalSize>10000000)throw Error('Combined reports exceed 10 MB.');input.disabled=true;const {group,kind}=input.dataset;const selectedAgency=agency();const text=(await Promise.all(files.map(f=>f.text()))).join('\n');parseReport(text,kind,selectedAgency,group,loaMapping);const filename=files.map(f=>f.name).join('; ');const response=await fetch('/api/reports',{method:'PUT',headers:{'Content-Type':'application/json','x-upload-password':password()},body:JSON.stringify({agency:selectedAgency,group,kind,text,filename})});const data=await response.json();if(!response.ok)throw Error(data.error||'Unable to save report.');reports[selectedAgency+'|'+group+'|'+kind]=data.report;$('message').textContent=data.report.rows.length+' records from '+files.length+' file'+(files.length===1?'':'s')+' saved in Azure for '+group+'. This upload slot was replaced.';setup();}catch(err){$('message').textContent=err.message;}finally{input.disabled=false;input.value='';}});setup();

async function loadShared(){try{const response=await fetch('/api/master',{cache:'no-store'});if(!response.ok)throw Error('Shared master is not available yet.');const saved=await response.json();master=(saved.rows||[]).map(row=>{const group=canonical(row.group);return group==='HQs'?{...row,agency:'G-8',group}:{...row,group}});$('master-status').textContent=saved.updatedAt?'Shared master updated '+new Date(saved.updatedAt).toLocaleString():'No shared master yet. Enter the upload password and upload the master budget.';setup();}catch(e){$('master-status').textContent=e.message;}}
$('save-master').addEventListener('click',async()=>{const button=$('save-master');button.disabled=true;try{requirePassword();if(!masterSource)throw Error('Select a replacement Master budget first.');const issues=replacementIssues();if(issues.length)throw Error(issues.join(' '));$('master-status').textContent='Publishing replacement files...';const r=await fetch('/api/master',{method:'PUT',headers:{'Content-Type':'application/json','x-upload-password':password()},body:JSON.stringify({rows:master,sourceBase64:masterSource})});if(r.status===401||r.status===403)throw Error('Enter the correct master upload password.');const data=await r.json();if(!r.ok)throw Error(data.error||'Could not save master.');master=data.rows;let loaData=null;if(stagedLoas){const lr=await fetch('/api/loas',{method:'PUT',headers:{'Content-Type':'application/json','x-upload-password':password()},body:JSON.stringify(stagedLoas)});loaData=await lr.json();if(!lr.ok)throw Error(loaData.error||'Master saved, but LOAs could not be saved.');loaMapping=loaData.mapping;loaOrganizations=loaData.organizations||{};stagedLoas=null;}$('master-status').textContent='Shared master updated '+new Date(data.updatedAt).toLocaleString();if(loaData)$('loa-status').textContent=Object.keys(loaMapping).length+' shared codes • Updated '+new Date(loaData.updatedAt).toLocaleString();masterSource=null;button.hidden=true;$('message').textContent=loaData?'Master budget and LOA cross-reference saved for all dashboard visitors.':'Master budget saved for all dashboard visitors.';setup();}catch(e){$('master-status').textContent='Replacement was not completed: '+e.message;$('message').textContent=e.message;}finally{button.disabled=false;}});loadShared();

function normalizeReports(source){const normalized={};for(const report of Object.values(source)){if(!report?.agency||!report?.kind)continue;const group=canonical(report.group);normalized[report.agency+'|'+group+'|'+report.kind]={...report,group,rows:(report.rows||[]).map(row=>({...row,group,mappedGroup:canonical(row.mappedGroup) }))};}return normalized;}
async function loadReports(){try{const r=await fetch('/api/reports',{cache:'no-store'});if(!r.ok)throw Error('Saved reports could not be loaded.');const data=await r.json();reports=normalizeReports({...data.reports,...reports});setup();}catch(e){$('message').textContent=e.message;}}
loadReports();

// Print a snapshot of one card, with its current agency and filter context.
for(const card of document.querySelectorAll('.panel:not(#upload-access)')){
 const button=document.createElement('button');button.type='button';button.className='print-card';button.textContent='Print card';
 const heading=card.querySelector('h2');button.setAttribute('aria-label','Print '+(heading?.textContent||'card'));
 const bar=card.querySelector('.section-head');if(bar)bar.append(button);else{const row=document.createElement('div');row.className='section-head';if(heading)row.append(heading);row.append(button);card.prepend(row);}
}
const printArea=document.createElement('div');printArea.id='card-print-area';document.body.append(printArea);
function clearCardPrint(){document.body.classList.remove('printing-card');printArea.replaceChildren();}
window.addEventListener('afterprint',clearCardPrint);
document.addEventListener('click',event=>{
 const button=event.target.closest('.print-card');if(!button)return;
 const card=button.closest('.panel,.metric');if(!card)return;
 const clone=card.cloneNode(true);clone.querySelectorAll('button,input,select,.button').forEach(el=>el.remove());clone.removeAttribute('id');clone.querySelectorAll('[id]').forEach(el=>el.removeAttribute('id'));
 const title=document.createElement('h1');title.textContent='ESD Travel Tool — '+agency();
 const scope=document.createElement('p');scope.textContent='Selected groups: '+[...selected].join(', ')+' • '+new Date().toLocaleString();
 printArea.replaceChildren(title,scope,clone);document.body.classList.add('printing-card');
 try{window.print();}catch(error){clearCardPrint();throw error;}
});

$('uploads').addEventListener('click',async event=>{
 const button=event.target.closest('.remove-voucher');if(!button)return;
 const group=button.dataset.group,selectedAgency=agency();
 try{requirePassword();if(!window.confirm('Remove the unsubmitted-voucher file for '+group+' from the shared dashboard?'))return;
 button.disabled=true;const r=await fetch('/api/reports',{method:'DELETE',headers:{'Content-Type':'application/json','x-upload-password':password()},body:JSON.stringify({agency:selectedAgency,group,kind:'voucher'})});const result=await r.json();if(!r.ok)throw Error(result.error||'Unable to remove file.');delete reports[selectedAgency+'|'+group+'|voucher'];setup();$('message').textContent='Unsubmitted-voucher file removed for '+group+'.';
 }catch(error){$('message').textContent=error.message;button.disabled=false;}
});

async function loadLoas(){try{const r=await fetch('/api/loas',{cache:'no-store'});if(!r.ok)throw Error('LOA reference unavailable.');const data=await r.json();loaMapping=data.mapping;loaOrganizations=data.organizations||{};$('loa-status').textContent=Object.keys(loaMapping).length+' shared codes'+(data.updatedAt?' • Updated '+new Date(data.updatedAt).toLocaleString():' • Original reference');}catch(e){$('loa-status').textContent=e.message;}}
$('loa-file').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{requirePassword();if(file.size>10000000)throw Error('LOA file exceeds 10 MB.');const buffer=await file.arrayBuffer(),bytes=new Uint8Array(buffer),workbook=new ExcelJS.Workbook();await workbook.xlsx.load(buffer);const rows=[];workbook.worksheets.forEach(sheet=>sheet.eachRow(row=>rows.push(row.values.slice(1).map(v=>v&&typeof v==='object'?v.result??v.text??'':v))));const key=value=>String(value??'').trim().toLowerCase().replace(/[^a-z0-9]+/g,''),header=rows.findIndex(row=>row.map(key).includes('lineofaccounting'));if(header<0)throw Error('Expected Line of Accounting, Directorate / DASA, and Organization columns.');const headers=rows[header].map(key),codeIndex=headers.indexOf('lineofaccounting'),groupIndex=headers.indexOf('directoratedasa'),organizationIndex=headers.indexOf('organization');if(groupIndex<0||organizationIndex<0)throw Error('Expected Directorate / DASA and Organization columns.');const mapping={},organizations={};for(const row of rows.slice(header+1)){if(!row[codeIndex]&&!row[groupIndex]&&!row[organizationIndex])continue;const code=String(row[codeIndex]||'').trim().toUpperCase(),group=canonical(row[groupIndex]),organization=String(row[organizationIndex]||'').trim();if(!code||!group||!organization)throw Error('Each LOA row needs a code, Directorate / DASA, and Organization.');if(!agencies[organization])throw Error('Unknown Organization '+organization+' for '+code+'.');if(mapping[code])throw Error('Duplicate code: '+code);mapping[code]=group;organizations[code]=organization;}if(!Object.keys(mapping).length)throw Error('No LOA codes found.');let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));stagedLoas={mapping,organizations,sourceBase64:btoa(binary)};const issues=refreshReplacementStatus();$('message').textContent=issues.length?issues.join(' '):'LOA and Master budget replacements match and are ready to publish.';}catch(e){stagedLoas=null;$('loa-status').textContent='Upload not staged: '+e.message;$('message').textContent=e.message;refreshReplacementStatus();}event.target.value='';});
$('publish-loas').addEventListener('click',()=>{});loadLoas();

let adminAttempt=0;
function hideAdmin(){adminAttempt++;document.querySelectorAll('.admin-only').forEach(card=>card.hidden=true);$('admin-status').textContent='';}
$('upload-password').addEventListener('input',hideAdmin);
async function unlockAdmin(){const attempt=++adminAttempt;const entered=password();if(!entered){$('admin-status').textContent='Enter the admin password.';return;}try{const r=await fetch('/api/verify-upload',{method:'POST',headers:{'x-upload-password':entered}});if(attempt!==adminAttempt)return;if(!r.ok)throw Error(r.status===401?'Incorrect admin password.':'Unable to verify password. Try again.');document.querySelectorAll('.admin-only').forEach(card=>card.hidden=false);$('admin-status').textContent='Admin controls unlocked.';}catch(e){if(attempt===adminAttempt)$('admin-status').textContent=e.message;}}
$('unlock-admin').addEventListener('click',unlockAdmin);
$('upload-password').addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();unlockAdmin();}});
$('upload-password').addEventListener('change',unlockAdmin);
