import loaMap from './loa-map.mjs';
export const agencies={'ASA(FM&C)':['Front Office','ABO','CE','FOI','FIARs (FOI)','AAFES'],'G-8':['HQs','CD','EMD','PA&E','FA49 (PA&E)']};
export const canonical=s=>{const raw=String(s??'').trim(),key=raw.toUpperCase().replace(/\s+/g,' '),compact=key.replace(/\s*\(\s*/g,'(').replace(/\s*\)\s*/g,')');return {'PAED':'PA&E','FIAR':'FIARs (FOI)','FIARS':'FIARs (FOI)','FIAR(FOI)':'FIARs (FOI)','FIARS(FOI)':'FIARs (FOI)','FIAR/FOI':'FIARs (FOI)','FIARS/FOI':'FIARs (FOI)','HQ':'HQs','HQS':'HQs','FA49(PAED)':'FA49 (PA&E)','FA49(PA&E)':'FA49 (PA&E)','PAED-(FA49)':'FA49 (PA&E)','PAED -(FA49)':'FA49 (PA&E)'}[compact]||raw};
export function csv(text){const rows=[];let row=[],value='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){value+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(value);value='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(value);rows.push(row);row=[];value='';}else value+=c;}if(value||row.length){row.push(value);rows.push(row);}if(quoted)throw Error('CSV contains an unclosed quoted field.');return rows;}
export function amount(value){let s=String(value??'').trim();if(!s||s==='-')return 0;const negative=s.startsWith('(');s=s.replace(/[$,()\s]/g,'');const n=Number(s);if(!Number.isFinite(n))throw Error('Invalid monetary value: '+value);return Math.round(n*(negative?-1:1)*100);}
export function parseReport(text,kind,agency,group,mapping=loaMap){const rows=csv(text.replace(/^\uFEFF/,'')),out=[];let header=null;const keys=new Set();let duplicates=0,found=false;
 for(const row of rows){if(row.includes(kind==='voucher'?'Organization/Suborganization':'Total Obligation')){header=row.map(x=>x.trim());found=true;continue;}if(!header||row.length!==header.length)continue;const r=Object.fromEntries(header.map((h,i)=>[h,row[i]?.trim()||'']));const id=r.TANUM||r.TANum;if(!id)continue;
 const code=(r.Organization||r['Organization/Suborganization']||'').trim().toUpperCase();const mapped=canonical(mapping[code]||'');if(mapped&&mapped!==group)throw Error(`Report code ${code} belongs to ${mapped}, not ${group}.`);
 const key=[id,r['Budget Label']||'',r['LOA']||'',r['Doc Name']||r['Document Name']||''].join('|');if(keys.has(key)){duplicates++;continue;}keys.add(key);
 const voucher=kind==='voucher';out.push({key,agency,group,mappedGroup:mapped,code,unmapped:!mapped,id,traveler:[r['Traveler First Name']||r['First Name'],r['Traveler Last Name']||r['Last Name']].filter(Boolean).join(' '),document:r['Document Name']||r['Doc Name'],departure:r['Departure Date'],destination:r['Location/Destination']||'',authorized:amount(r[voucher?'Amount of Authorization':'Total Auth.']),obligated:voucher?0:amount(r['Total Obligation']),voucherAmount:voucher?0:amount(r['Total Voucher']),days:voucher?Number(r['Days Since End of Trip']||0):null});
 }if(!found)throw Error('Expected '+(kind==='voucher'?'Unsubmitted Voucher':'Total Obligation')+' report headers.');return {rows:out,duplicates};}
export function parseMaster(rows){const normalized=rows.map(row=>row.map(value=>String(value??'').trim())),headerKey=value=>String(value??'').trim().toLowerCase().replace(/[^a-z0-9]+/g,''),h=normalized.findIndex(row=>{const keys=row.map(headerKey);return keys.includes('organization')&&(keys.includes('dasa')||keys.includes('directoratedasa'))&&keys.includes('budget')&&keys.includes('budgetreceivedtodate');});if(h<0)throw Error('Expected Organization, Directorate / DASA, Budget and Budget Received to Date columns.');const headers=normalized[h].map(headerKey),out=[],seen=new Set(),value=(row,...names)=>{for(const name of names){const index=headers.indexOf(name);if(index>=0)return row[index];}};for(const row of rows.slice(h+1)){const organization=value(row,'organization'),dasa=value(row,'dasa','directoratedasa');if(!organization||!dasa||String(dasa).trim().toLowerCase()==='total')continue;const group=canonical(dasa),agency=group==='HQs'?'G-8':String(organization).trim();if(!agencies[agency])throw Error('Unknown Organization '+agency+' for '+group);const key=agency+'|'+group;if(seen.has(key))throw Error('Duplicate master budget '+key);seen.add(key);out.push({agency,group,budget:amount(value(row,'budget')),received:amount(value(row,'budgetreceivedtodate')),baselineObligated:amount(value(row,'obligated'))});}if(!out.length)throw Error('No master budget records.');return out;}
export function summarize(master,reports,agency,groups){return groups.map(group=>{const m=master.find(x=>x.agency===agency&&x.group===group),t=reports[agency+'|'+group+'|travel'],v=reports[agency+'|'+group+'|voucher'];const travel=t?.rows||[],vouchers=v?.rows||[],obligated=t?travel.reduce((n,r)=>n+r.obligated,0):null;const voucherIds=new Set(vouchers.map(r=>r.id));return {group,budget:m?.budget??null,received:m?.received??null,obligated,remaining:m&&obligated!==null?m.received-obligated:null,travel,unsubmitted:vouchers,completed:travel.filter(r=>r.voucherAmount>0&&!voucherIds.has(r.id)),travelStatus:t?'Uploaded':'Not supplied',voucherStatus:v?'Uploaded':'Not supplied'};});}
